/* tslint:disable */
/* eslint-disable */
/**
 * Janun API
 * REST API for Janun Backend Service by Team QuantumGuys
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Channel } from './Channel';
import {
    ChannelFromJSON,
    ChannelFromJSONTyped,
    ChannelToJSON,
} from './Channel';

/**
 * 
 * @export
 * @interface ChannelsPage
 */
export interface ChannelsPage {
    /**
     * 
     * @type {Array<Channel>}
     * @memberof ChannelsPage
     */
    data?: Array<Channel>;
    /**
     * 
     * @type {number}
     * @memberof ChannelsPage
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof ChannelsPage
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof ChannelsPage
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof ChannelsPage
     */
    totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ChannelsPage
     */
    last?: boolean;
}

/**
 * Check if a given object implements the ChannelsPage interface.
 */
export function instanceOfChannelsPage(value: object): value is ChannelsPage {
    return true;
}

export function ChannelsPageFromJSON(json: any): ChannelsPage {
    return ChannelsPageFromJSONTyped(json, false);
}

export function ChannelsPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelsPage {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ChannelFromJSON)),
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'last': json['last'] == null ? undefined : json['last'],
    };
}

export function ChannelsPageToJSON(value?: ChannelsPage | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ChannelToJSON)),
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'last': value['last'],
    };
}

