/* tslint:disable */
/* eslint-disable */
/**
 * Janun API
 * REST API for Janun Backend Service by Team QuantumGuys
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChannelMin
 */
export interface ChannelMin {
    /**
     * 
     * @type {string}
     * @memberof ChannelMin
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof ChannelMin
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ChannelMin
     */
    premium?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ChannelMin
     */
    subscribed?: boolean;
}

/**
 * Check if a given object implements the ChannelMin interface.
 */
export function instanceOfChannelMin(value: object): value is ChannelMin {
    return true;
}

export function ChannelMinFromJSON(json: any): ChannelMin {
    return ChannelMinFromJSONTyped(json, false);
}

export function ChannelMinFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelMin {
    if (json == null) {
        return json;
    }
    return {
        
        'slug': json['slug'] == null ? undefined : json['slug'],
        'name': json['name'] == null ? undefined : json['name'],
        'premium': json['premium'] == null ? undefined : json['premium'],
        'subscribed': json['subscribed'] == null ? undefined : json['subscribed'],
    };
}

export function ChannelMinToJSON(value?: ChannelMin | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'slug': value['slug'],
        'name': value['name'],
        'premium': value['premium'],
        'subscribed': value['subscribed'],
    };
}

