/* tslint:disable */
/* eslint-disable */
/**
 * Janun API
 * REST API for Janun Backend Service by Team QuantumGuys
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentCreateRequest
 */
export interface CommentCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof CommentCreateRequest
     */
    content?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CommentCreateRequest
     */
    anonymous?: boolean;
}

/**
 * Check if a given object implements the CommentCreateRequest interface.
 */
export function instanceOfCommentCreateRequest(value: object): value is CommentCreateRequest {
    return true;
}

export function CommentCreateRequestFromJSON(json: any): CommentCreateRequest {
    return CommentCreateRequestFromJSONTyped(json, false);
}

export function CommentCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : json['content'],
        'anonymous': json['anonymous'] == null ? undefined : json['anonymous'],
    };
}

export function CommentCreateRequestToJSON(value?: CommentCreateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'content': value['content'],
        'anonymous': value['anonymous'],
    };
}

