/* tslint:disable */
/* eslint-disable */
/**
 * Janun API
 * REST API for Janun Backend Service by Team QuantumGuys
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Comment } from './Comment';
import {
    CommentFromJSON,
    CommentFromJSONTyped,
    CommentToJSON,
} from './Comment';

/**
 * 
 * @export
 * @interface CommentsPage
 */
export interface CommentsPage {
    /**
     * 
     * @type {Array<Comment>}
     * @memberof CommentsPage
     */
    data?: Array<Comment>;
    /**
     * 
     * @type {number}
     * @memberof CommentsPage
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof CommentsPage
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof CommentsPage
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof CommentsPage
     */
    totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CommentsPage
     */
    last?: boolean;
}

/**
 * Check if a given object implements the CommentsPage interface.
 */
export function instanceOfCommentsPage(value: object): value is CommentsPage {
    return true;
}

export function CommentsPageFromJSON(json: any): CommentsPage {
    return CommentsPageFromJSONTyped(json, false);
}

export function CommentsPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentsPage {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(CommentFromJSON)),
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'last': json['last'] == null ? undefined : json['last'],
    };
}

export function CommentsPageToJSON(value?: CommentsPage | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(CommentToJSON)),
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'last': value['last'],
    };
}

