/* tslint:disable */
/* eslint-disable */
/**
 * Janun API
 * REST API for Janun Backend Service by Team QuantumGuys
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MediaMin
 */
export interface MediaMin {
    /**
     * 
     * @type {string}
     * @memberof MediaMin
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof MediaMin
     */
    type?: string;
}

/**
 * Check if a given object implements the MediaMin interface.
 */
export function instanceOfMediaMin(value: object): value is MediaMin {
    return true;
}

export function MediaMinFromJSON(json: any): MediaMin {
    return MediaMinFromJSONTyped(json, false);
}

export function MediaMinFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaMin {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function MediaMinToJSON(value?: MediaMin | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
        'type': value['type'],
    };
}

