/* tslint:disable */
/* eslint-disable */
/**
 * Janun API
 * REST API for Janun Backend Service by Team QuantumGuys
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostMin
 */
export interface PostMin {
    /**
     * 
     * @type {string}
     * @memberof PostMin
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof PostMin
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof PostMin
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof PostMin
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof PostMin
     */
    type?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PostMin
     */
    premium?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PostMin
     */
    reaction?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PostMin
     */
    reacted?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PostMin
     */
    reported?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PostMin
     */
    commented?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PostMin
     */
    subscribed?: boolean;
}

/**
 * Check if a given object implements the PostMin interface.
 */
export function instanceOfPostMin(value: object): value is PostMin {
    return true;
}

export function PostMinFromJSON(json: any): PostMin {
    return PostMinFromJSONTyped(json, false);
}

export function PostMinFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostMin {
    if (json == null) {
        return json;
    }
    return {
        
        'slug': json['slug'] == null ? undefined : json['slug'],
        'title': json['title'] == null ? undefined : json['title'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
        'type': json['type'] == null ? undefined : json['type'],
        'premium': json['premium'] == null ? undefined : json['premium'],
        'reaction': json['reaction'] == null ? undefined : json['reaction'],
        'reacted': json['reacted'] == null ? undefined : json['reacted'],
        'reported': json['reported'] == null ? undefined : json['reported'],
        'commented': json['commented'] == null ? undefined : json['commented'],
        'subscribed': json['subscribed'] == null ? undefined : json['subscribed'],
    };
}

export function PostMinToJSON(value?: PostMin | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'slug': value['slug'],
        'title': value['title'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
        'type': value['type'],
        'premium': value['premium'],
        'reaction': value['reaction'],
        'reacted': value['reacted'],
        'reported': value['reported'],
        'commented': value['commented'],
        'subscribed': value['subscribed'],
    };
}

