/* tslint:disable */
/* eslint-disable */
/**
 * Janun API
 * REST API for Janun Backend Service by Team QuantumGuys
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Post } from './Post';
import {
    PostFromJSON,
    PostFromJSONTyped,
    PostToJSON,
} from './Post';

/**
 * 
 * @export
 * @interface PostsPage
 */
export interface PostsPage {
    /**
     * 
     * @type {Array<Post>}
     * @memberof PostsPage
     */
    data?: Array<Post>;
    /**
     * 
     * @type {number}
     * @memberof PostsPage
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof PostsPage
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PostsPage
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PostsPage
     */
    totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PostsPage
     */
    last?: boolean;
}

/**
 * Check if a given object implements the PostsPage interface.
 */
export function instanceOfPostsPage(value: object): value is PostsPage {
    return true;
}

export function PostsPageFromJSON(json: any): PostsPage {
    return PostsPageFromJSONTyped(json, false);
}

export function PostsPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostsPage {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(PostFromJSON)),
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'last': json['last'] == null ? undefined : json['last'],
    };
}

export function PostsPageToJSON(value?: PostsPage | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(PostToJSON)),
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'last': value['last'],
    };
}

