/* tslint:disable */
/* eslint-disable */
/**
 * Janun API
 * REST API for Janun Backend Service by Team QuantumGuys
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Profile
 */
export interface Profile {
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    avatar?: string;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    bio?: string;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    country?: string;
}

/**
 * Check if a given object implements the Profile interface.
 */
export function instanceOfProfile(value: object): value is Profile {
    return true;
}

export function ProfileFromJSON(json: any): Profile {
    return ProfileFromJSONTyped(json, false);
}

export function ProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): Profile {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
        'bio': json['bio'] == null ? undefined : json['bio'],
        'city': json['city'] == null ? undefined : json['city'],
        'country': json['country'] == null ? undefined : json['country'],
    };
}

export function ProfileToJSON(value?: Profile | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'avatar': value['avatar'],
        'bio': value['bio'],
        'city': value['city'],
        'country': value['country'],
    };
}

