/* tslint:disable */
/* eslint-disable */
/**
 * Janun API
 * REST API for Janun Backend Service by Team QuantumGuys
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserMin } from './UserMin';
import {
    UserMinFromJSON,
    UserMinFromJSONTyped,
    UserMinToJSON,
} from './UserMin';

/**
 * 
 * @export
 * @interface Reaction
 */
export interface Reaction {
    /**
     * 
     * @type {number}
     * @memberof Reaction
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Reaction
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof Reaction
     */
    createdAgo?: string;
    /**
     * 
     * @type {string}
     * @memberof Reaction
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof Reaction
     */
    updatedAgo?: string;
    /**
     * 
     * @type {UserMin}
     * @memberof Reaction
     */
    user?: UserMin;
    /**
     * 
     * @type {string}
     * @memberof Reaction
     */
    postSlug?: string;
    /**
     * 
     * @type {string}
     * @memberof Reaction
     */
    type?: string;
}

/**
 * Check if a given object implements the Reaction interface.
 */
export function instanceOfReaction(value: object): value is Reaction {
    return true;
}

export function ReactionFromJSON(json: any): Reaction {
    return ReactionFromJSONTyped(json, false);
}

export function ReactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Reaction {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'createdAgo': json['createdAgo'] == null ? undefined : json['createdAgo'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
        'updatedAgo': json['updatedAgo'] == null ? undefined : json['updatedAgo'],
        'user': json['user'] == null ? undefined : UserMinFromJSON(json['user']),
        'postSlug': json['postSlug'] == null ? undefined : json['postSlug'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function ReactionToJSON(value?: Reaction | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'createdAt': value['createdAt'],
        'createdAgo': value['createdAgo'],
        'updatedAt': value['updatedAt'],
        'updatedAgo': value['updatedAgo'],
        'user': UserMinToJSON(value['user']),
        'postSlug': value['postSlug'],
        'type': value['type'],
    };
}

