/* tslint:disable */
/* eslint-disable */
/**
 * Janun API
 * REST API for Janun Backend Service by Team QuantumGuys
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Report } from './Report';
import {
    ReportFromJSON,
    ReportFromJSONTyped,
    ReportToJSON,
} from './Report';

/**
 * 
 * @export
 * @interface ReportsPage
 */
export interface ReportsPage {
    /**
     * 
     * @type {Array<Report>}
     * @memberof ReportsPage
     */
    data?: Array<Report>;
    /**
     * 
     * @type {number}
     * @memberof ReportsPage
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof ReportsPage
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof ReportsPage
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof ReportsPage
     */
    totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ReportsPage
     */
    last?: boolean;
}

/**
 * Check if a given object implements the ReportsPage interface.
 */
export function instanceOfReportsPage(value: object): value is ReportsPage {
    return true;
}

export function ReportsPageFromJSON(json: any): ReportsPage {
    return ReportsPageFromJSONTyped(json, false);
}

export function ReportsPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportsPage {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ReportFromJSON)),
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'last': json['last'] == null ? undefined : json['last'],
    };
}

export function ReportsPageToJSON(value?: ReportsPage | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ReportToJSON)),
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'last': value['last'],
    };
}

