/* tslint:disable */
/* eslint-disable */
/**
 * Janun API
 * REST API for Janun Backend Service by Team QuantumGuys
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReportUpdateRequest
 */
export interface ReportUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof ReportUpdateRequest
     */
    status?: string;
}

/**
 * Check if a given object implements the ReportUpdateRequest interface.
 */
export function instanceOfReportUpdateRequest(value: object): value is ReportUpdateRequest {
    return true;
}

export function ReportUpdateRequestFromJSON(json: any): ReportUpdateRequest {
    return ReportUpdateRequestFromJSONTyped(json, false);
}

export function ReportUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ReportUpdateRequestToJSON(value?: ReportUpdateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
    };
}

