/* tslint:disable */
/* eslint-disable */
/**
 * Janun API
 * REST API for Janun Backend Service by Team QuantumGuys
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TagMin
 */
export interface TagMin {
    /**
     * 
     * @type {string}
     * @memberof TagMin
     */
    name?: string;
}

/**
 * Check if a given object implements the TagMin interface.
 */
export function instanceOfTagMin(value: object): value is TagMin {
    return true;
}

export function TagMinFromJSON(json: any): TagMin {
    return TagMinFromJSONTyped(json, false);
}

export function TagMinFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagMin {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function TagMinToJSON(value?: TagMin | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

