/* tslint:disable */
/* eslint-disable */
/**
 * Janun API
 * REST API for Janun Backend Service by Team QuantumGuys
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChannelMin } from './ChannelMin';
import {
    ChannelMinFromJSON,
    ChannelMinFromJSONTyped,
    ChannelMinToJSON,
} from './ChannelMin';
import type { TagMin } from './TagMin';
import {
    TagMinFromJSON,
    TagMinFromJSONTyped,
    TagMinToJSON,
} from './TagMin';

/**
 * 
 * @export
 * @interface Thread
 */
export interface Thread {
    /**
     * 
     * @type {string}
     * @memberof Thread
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof Thread
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Thread
     */
    premium?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Thread
     */
    subscribed?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Thread
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Thread
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof Thread
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof Thread
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof Thread
     */
    logo?: string;
    /**
     * 
     * @type {string}
     * @memberof Thread
     */
    cover?: string;
    /**
     * 
     * @type {Set<string>}
     * @memberof Thread
     */
    links?: Set<string>;
    /**
     * 
     * @type {number}
     * @memberof Thread
     */
    subscriberCount?: number;
    /**
     * 
     * @type {number}
     * @memberof Thread
     */
    postCount?: number;
    /**
     * 
     * @type {number}
     * @memberof Thread
     */
    tagCount?: number;
    /**
     * 
     * @type {ChannelMin}
     * @memberof Thread
     */
    channel?: ChannelMin;
    /**
     * 
     * @type {Set<TagMin>}
     * @memberof Thread
     */
    tags?: Set<TagMin>;
}

/**
 * Check if a given object implements the Thread interface.
 */
export function instanceOfThread(value: object): value is Thread {
    return true;
}

export function ThreadFromJSON(json: any): Thread {
    return ThreadFromJSONTyped(json, false);
}

export function ThreadFromJSONTyped(json: any, ignoreDiscriminator: boolean): Thread {
    if (json == null) {
        return json;
    }
    return {
        
        'slug': json['slug'] == null ? undefined : json['slug'],
        'name': json['name'] == null ? undefined : json['name'],
        'premium': json['premium'] == null ? undefined : json['premium'],
        'subscribed': json['subscribed'] == null ? undefined : json['subscribed'],
        'description': json['description'] == null ? undefined : json['description'],
        'language': json['language'] == null ? undefined : json['language'],
        'city': json['city'] == null ? undefined : json['city'],
        'country': json['country'] == null ? undefined : json['country'],
        'logo': json['logo'] == null ? undefined : json['logo'],
        'cover': json['cover'] == null ? undefined : json['cover'],
        'links': json['links'] == null ? undefined : json['links'],
        'subscriberCount': json['subscriberCount'] == null ? undefined : json['subscriberCount'],
        'postCount': json['postCount'] == null ? undefined : json['postCount'],
        'tagCount': json['tagCount'] == null ? undefined : json['tagCount'],
        'channel': json['channel'] == null ? undefined : ChannelMinFromJSON(json['channel']),
        'tags': json['tags'] == null ? undefined : (new Set((json['tags'] as Array<any>).map(TagMinFromJSON))),
    };
}

export function ThreadToJSON(value?: Thread | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'slug': value['slug'],
        'name': value['name'],
        'premium': value['premium'],
        'subscribed': value['subscribed'],
        'description': value['description'],
        'language': value['language'],
        'city': value['city'],
        'country': value['country'],
        'logo': value['logo'],
        'cover': value['cover'],
        'links': value['links'] == null ? undefined : Array.from(value['links'] as Set<any>),
        'subscriberCount': value['subscriberCount'],
        'postCount': value['postCount'],
        'tagCount': value['tagCount'],
        'channel': ChannelMinToJSON(value['channel']),
        'tags': value['tags'] == null ? undefined : (Array.from(value['tags'] as Set<any>).map(TagMinToJSON)),
    };
}

