/* tslint:disable */
/* eslint-disable */
/**
 * Janun API
 * REST API for Janun Backend Service by Team QuantumGuys
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserMin
 */
export interface UserMin {
    /**
     * 
     * @type {string}
     * @memberof UserMin
     */
    username?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserMin
     */
    premium?: boolean;
}

/**
 * Check if a given object implements the UserMin interface.
 */
export function instanceOfUserMin(value: object): value is UserMin {
    return true;
}

export function UserMinFromJSON(json: any): UserMin {
    return UserMinFromJSONTyped(json, false);
}

export function UserMinFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserMin {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
        'premium': json['premium'] == null ? undefined : json['premium'],
    };
}

export function UserMinToJSON(value?: UserMin | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'username': value['username'],
        'premium': value['premium'],
    };
}

